server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/guli_pms?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host:192.168.188.131
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/pms/**/*.xml
#logging:
#  level:
#    com.atguigu.gmall.pms: debug
  # 默认日志文件名
  # file: log
  # 默认日志路径
  # path: ./log
  # logback.xml路径，默认为classpath:logback.xml
  # config: ./logback.xml

